<b>np.reshape()</b>

In [1]:
import numpy as np

vendas = np.array([200, 220, 250, 210, 300, 280, 230, 210, 220, 240, 230, 210, 280, 220])

vendas_reshaped = np.reshape(vendas, (2, 7))
print(vendas_reshaped)

[[200 220 250 210 300 280 230]
 [210 220 240 230 210 280 220]]


In [23]:
import numpy as np

rng = np.random.default_rng(seed=42)
vendas = rng.integers(low=20, high=200, size=30, endpoint=True)
print(vendas)

[ 36 160 138  99  98 175  35 146  56  37 115 196 153 157 149 162 112  43
 171 101 110  87  53 187 161 136  92 168 118 100]


In [24]:
vendas_semanais = np.reshape(vendas, (5, 6))
print(vendas_semanais)

[[ 36 160 138  99  98 175]
 [ 35 146  56  37 115 196]
 [153 157 149 162 112  43]
 [171 101 110  87  53 187]
 [161 136  92 168 118 100]]


In [25]:
total_vendas_semana = vendas_semanais.sum(axis=1)
print(total_vendas_semana)

[706 585 776 709 775]


In [26]:
media_vendas_semana = vendas_semanais.mean(axis=1)
print(media_vendas_semana)

[117.66666667  97.5        129.33333333 118.16666667 129.16666667]


In [27]:
media_vendas_dia = vendas_semanais.mean(axis=0)
print(media_vendas_dia)

[111.2 140.  109.  110.6  99.2 140.2]
