Gerador de Numeros Aleatorios

In [3]:
import numpy as np

rng = np.random.default_rng()
print(rng)

Generator(PCG64)


In [25]:
numero_aleatorio = rng.random() * 10
print(f'{numero_aleatorio:.3f}')

7.426


In [31]:
array_aleatorio = rng.random(5)
print(array_aleatorio)

[0.16008692 0.42875042 0.35849563 0.38538878 0.82330025]


In [39]:
rng = np.random.default_rng(seed=42)
dados_vendas = rng.integers(low=50, high=200, size=30)
print(dados_vendas)

[ 63 166 148 115 114 178  62 154  80  64 128 196 160 164 157 167 126  69
 175 117 125 105  77 189 167 146 110 173 131 116]


In [40]:
print(np.max(dados_vendas))

196


In [42]:
print(np.argmax(dados_vendas) + 1)

12


In [43]:
print(f'Dia com mais vendas: {np.argmax(dados_vendas) + 1}.')

Dia com mais vendas: 12.


In [44]:
print(f'Dia com menos vendas: {np.argmin(dados_vendas) + 1}.')

Dia com menos vendas: 7.


In [46]:
media_vendas = np.mean(dados_vendas)
print(f'A media de vendas durante o mes foi de {int(media_vendas)} vendas por dia.')

A media de vendas durante o mes foi de 131 vendas por dia.


<b>Filtros</b>

In [47]:
import numpy as np

salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

media_salarial = np.mean(salarios)

print(media_salarial)

3714.285714285714


In [48]:
funcionarios_acima_media = np.where(salarios > media_salarial)
print(funcionarios_acima_media)

(array([2, 4, 5, 6]),)


In [49]:
print(salarios[funcionarios_acima_media])

[4000 4500 4000 5000]


In [50]:
print(salarios[salarios > media_salarial])

[4000 4500 4000 5000]


In [51]:
import numpy as np

salarios = np.array([3000, 2500, 3500, 4000, 2000, 4500, 3000, 3800, 4800])
print(salarios)
print(type(salarios))

[3000 2500 3500 4000 2000 4500 3000 3800 4800]
<class 'numpy.ndarray'>


In [52]:
media_salarial = np.mean(salarios)
print(media_salarial)

3455.5555555555557


In [53]:
print(np.where(salarios > media_salarial))

(array([2, 3, 5, 7, 8]),)


In [54]:
print(salarios[salarios > media_salarial])

[3500 4000 4500 3800 4800]


In [55]:
print(salarios > media_salarial)

[False False  True  True False  True False  True  True]


In [56]:
print(np.sum(salarios > media_salarial))

5


In [58]:
print(True == 1)

True


In [59]:
print(False == 0)

True


In [60]:
print(sum([True, False, True, False]))

2


In [62]:
funcionarios_acima_media = np.sum(salarios > media_salarial)
print(f'{funcionarios_acima_media} funcionarios possuem salario acima da media.')

5 funcionarios possuem salario acima da media.


In [63]:
print(np.count_nonzero(salarios > media_salarial))

5


In [71]:
print(np.unique(salarios > media_salarial))

[False  True]


In [72]:
import numpy as np

tempos_ciclo = np.array([5.5, 5.7, 5.9, 6.0, 5.8, 5.6, 5.7, 7.2, 4.8])
media = np.mean(tempos_ciclo)
print(media)

5.8


In [76]:
desvio_padrao = np.std(tempos_ciclo)
print(desvio_padrao)

0.592546294487706


In [78]:
condicao = tempos_ciclo > 5
print(np.where(condicao))

(array([0, 1, 2, 3, 4, 5, 6, 7]),)


In [87]:
condicao = (tempos_ciclo > media + 2 * desvio_padrao) | (tempos_ciclo < media - 2 * desvio_padrao)
anomalias = np.where(condicao)
print(anomalias)

(array([7]),)


In [88]:
print(tempos_ciclo[anomalias])

[7.2]


In [89]:
print(tempos_ciclo[condicao])

[7.2]


In [90]:
print(f'Os tempos que estao na condicao pedida sao {tempos_ciclo[condicao]}.')

Os tempos que estao na condicao pedida sao [7.2].
