In [1]:
import numpy as np
import pandas as pd



In [2]:
X = np.array([[1.2, 3], 
              [1.5, 4], 
              [1.0, 2], 
              [2.0, 5], 
              [1.8, 4]])

print("X:")
print(X)

X:
[[1.2 3. ]
 [1.5 4. ]
 [1.  2. ]
 [2.  5. ]
 [1.8 4. ]]


In [3]:
W = np.array([[80],   # Weight for size
              [20]])  # Weight for number of rooms

print("\nW (in €000):")
print(W)


W (in €000):
[[80]
 [20]]


In [4]:
y_pred = X @ W  # or np.dot(X, W)
print("\nPredicted Price (X @ W):")
print(y_pred)



Predicted Price (X @ W):
[[156.]
 [200.]
 [120.]
 [260.]
 [224.]]


In [5]:
Y = np.array([[151],
              [204],
              [117],
              [266],
              [222]])

print("\nActual Prices (Y):")
print(Y)
print("\nShape of Y:", Y.shape)


Actual Prices (Y):
[[151]
 [204]
 [117]
 [266]
 [222]]

Shape of Y: (5, 1)


In [6]:
error = Y - y_pred

print("Error:")
print(error)

Error:
[[-5.]
 [ 4.]
 [-3.]
 [ 6.]
 [-2.]]


In [7]:
SSE = error.T @ error

print("\nSSE")
print(SSE)


SSE
[[90.]]


In [13]:
W_new = np.array([[81],
                    [19]])

y_pred_new = X @ W_new
error_new = Y - y_pred_new
SSE_new = error_new.T @ error_new
SSE_new

array([[137.53]])